---
sidebar: sidebar 
permalink: learn-well-architected-dashboard.html 
keywords: well-architected, best practices, well-architected system, best practices, well-architected framework, well-architected configurations, system management, system optimization, system configuration, system analysis 
summary: O painel de controle bem estruturado no NetApp Console analisa as configurações do sistema em busca de confiabilidade, segurança, excelência operacional, otimização de custos e eficiência de desempenho, fornecendo insights e recomendações para ajudar você a alcançar excelência operacional. 
---
= Saiba mais sobre o painel de controle bem estruturado no NetApp Console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O NetApp Workload Factory ajuda você a manter e operar configurações confiáveis, seguras, eficientes e econômicas, alinhadas com as estruturas bem arquitetadas para o tipo de storage que você utiliza. O painel bem arquitetado no NetApp Console oferece uma visão unificada entre contas e regiões, ajuda as equipes a identificar e priorizar riscos e suporta regras personalizadas para requisitos específicos. As verificações automáticas diárias das configurações do seu sistema de storage fornecem insights e recomendações para ajudar você a otimizar seus ambientes de storage.



[[how-it-works]]
== Como funciona

O Workload Factory analisa suas configurações diariamente. A análise fornece um status bem arquitetado, insights e recomendações para ajudar você a otimizar seus ambientes de storage.

Após a conclusão da análise diária, as configurações aparecem como "otimizadas" ou "não otimizadas" no painel de arquitetura bem arquitetada. Você encontrará problemas de configuração por categoria da estrutura (confiabilidade, segurança, excelência operacional, otimização de custos e eficiência de desempenho) e uma lista de problemas de configuração e recomendações. O Workload Factory pode corrigir alguns problemas automaticamente, enquanto outros exigem intervenção manual. Nesse caso, a recomendação fornece instruções detalhadas para ajudar você a implementar as alterações.

Você pode descartar a análise de configurações que não se aplicam aos seus ambientes. Descartar configurações evita alertas desnecessários e resultados de otimização imprecisos.



[[why-it-matters]]
== Por que isso importa

O Workload Factory aplica as melhores práticas a grandes ambientes de storage, banco de dados e VMware, combinando avaliação contínua com insights de recomendações e remediação. A remediação automatizada reduz erros humanos, garante gerenciamento uniforme e preserva o desempenho e a confiabilidade em toda a sua infraestrutura de sistemas.



[[supported-storage-systems]]
== Sistemas de storage suportados

O painel de controle bem estruturado do Console oferece suporte aos seguintes sistemas de storage:

* Amazon FSx for NetApp ONTAP
* Cloud Volumes ONTAP no Microsoft Azure




[[get-started-with-netapp-console-to-detect-and-fix-system-misconfigurations]]
== Comece a usar o NetApp Console para detectar e corrigir configurações incorretas do sistema

Para começar a usar o NetApp Console, inscreva-se, adicione suas credenciais e estabeleça conectividade para gerenciar seus recursos e otimizar as configurações do sistema.

link:http://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Fluxo de trabalho inicial para NetApp Console (aplicativo SaaS)"^]



[[related-information]]
== Informações relacionadas

* link:fsx/improve-configurations-fsx.html["Implementar FSx bem arquitetado para sistemas de arquivos ONTAP"^]
* link:cvo/improve-configurations-cvo.html["Implemente sistemas Cloud Volumes ONTAP bem arquitetados"^]

