---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, well-architected, well-architected dashboard, amazon fsx for netapp ontap, fsx for ontap, cloud volumes ontap, microsoft azure' 
summary: Descubra as novidades do painel de controle bem estruturado no NetApp Console. 
---
= O que há de novo no painel bem arquitetado do NetApp Console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Descubra as novidades do painel de controle bem estruturado no NetApp Console.



[[17-august-2026]]
== 17 de agosto de 2026



[[fsx-for-ontap-support-in-the-well-architected-dashboard-in-netapp-console]]
=== Suporte a FSx for ONTAP no painel bem arquitetado no NetApp Console

O painel de controle bem estruturado no NetApp Console está disponível para Amazon FSx for NetApp ONTAP.

link:https://docs.netapp.com/us-en/console-well-architected/fsx/configuration-analysis-fsx.html["Saiba mais sobre a análise de configuração do Amazon FSx for NetApp ONTAP"]



[[updated-configuration-names-in-the-well-architected-dashboard]]
=== Nomes de configuração atualizados no painel de controle bem arquitetado

O painel bem arquitetado no NetApp Console agora inclui novos nomes de configuração de storage.

A tabela a seguir lista os nomes de configuração antigos e seus respectivos nomes de configuração novos no dashboard bem arquitetado.

[cols="1,1"]
|===
| Nome da configuração antiga | Novo nome de configuração 


| Agendar backups de volumes | Backups de volume 


| Limite de capacidade do SSD | Espaço livre de capacidade do SSD 


| Limite de capacidade de arquivo | Espaço livre na capacidade de arquivos 


| Confiabilidade dos dados de retenção a longo prazo | Rótulos de política de replicação 


| Snapshots locais programados | Política do Snapshot 


| Exclua backups desnecessários | Expiração do backup 


| Excluir Snapshots desnecessários | Expiração do Snapshot 


| Capacidade subutilizada de SSD | Capacidade SSD superdimensionada 


| Dispositivos de bloco inativos | Dispositivos de bloco inativos (LUN) 


| Otimize o TCO ao hierarquizar dados frios | Hierarquização de dados frios 


| Relatório de capacidade lógica de volume | Relatório de capacidade visível para o host 


| FlexGroup reequilíbrio de volumes | Reequilibrar volumes FlexGroup 


| FlexVol volumes reequilíbrio | Reequilibrar volumes FlexVol 


| Modo de gravação do relacionamento de cache | FlexCache modo de escrita 


| Otimizar o tamanho do volume de cache | FlexCache tamanho da réplica 


| Acesso não autorizado ao volume | Acesso não autorizado ao volume iSCSI 


| ARP/AI desativado | Proteção contra ransomware (ARP/AI) 
|===


[[well-architected-issues-displayed-in-netapp-console-systems-page]]
=== Problemas bem arquitetados exibidos na página de Sistemas da NetApp Console

As notificações para problemas de arquitetura bem definida estão disponíveis para o Cloud Volumes ONTAP no Microsoft Azure na página Sistemas de gerenciamento de storage no NetApp Console. Esse recurso ajuda você a identificar rapidamente problemas de configuração em seus sistemas Cloud Volumes ONTAP no Azure e a navegar até o painel de arquitetura bem definida de cargas de trabalho a partir da notificação.



[[10-august-2026]]
== 10 de agosto de 2026



[[google-cloud-netapp-volumes-support-in-the-well-architected-dashboard]]
=== Suporte para o Google Cloud NetApp Volumes no painel bem arquitetado

O painel do NetApp Console agora é compatível com o Google Cloud NetApp Volumes. Os administradores de armazenamento podem visualizar o status de seus pools de armazenamento e configurações, receber recomendações para melhorar a eficiência, o custo, o desempenho, a confiabilidade e a segurança, além de tomar medidas para otimizar as operações e seguir as melhores práticas.

Saiba mais sobre link:https://docs.netapp.com/us-en/console-well-architected/gcnv/configuration-analysis-gcnv.html["Análise de configuração para o Google Cloud NetApp Volumes"].



[[03-august-2026]]
== 03 de agosto de 2026



[[fix-dismiss-and-reactivate-configurations-for-cloud-volumes-ontap-in-microsoft-azure]]
=== Corrija, descarte e reative configurações para Cloud Volumes ONTAP no Microsoft Azure

O painel de controle bem estruturado no NetApp Console agora permite que você corrija recomendações de configuração para seus sistemas Cloud Volumes ONTAP.

Você também pode descartar uma ou mais configurações da análise de arquitetura bem estruturada. Isso permite ignorar configurações específicas que não se aplicam ao seu ambiente.

Se desejar incluir posteriormente uma configuração descartada, você pode reativá-la no painel de controle bem arquitetado. Isso restaura a configuração à análise e permite que você receba recomendações e correções para ela.

link:https://docs.netapp.com/us-en/console-well-architected/cvo/\improve-configurations-cvo.html["Corrija, descarte e reative configurações para Cloud Volumes ONTAP no Microsoft Azure"]



[[20-july-2026]]
== 20 de julho de 2026



[[introducing-the-well-architected-dashboard-in-netapp-console]]
=== Apresentando o painel bem arquitetado no NetApp Console

O painel de controle bem-arquitetado no NetApp Console oferece uma visão unificada dos seus sistemas de storage e configurações em todas as contas e regiões. O painel fornece insights e recomendações para ajudar você a alcançar excelência operacional. Você pode visualizar o status bem-arquitetado das suas configurações, problemas de configuração organizados pelos pilares da estrutura bem-arquitetada para o tipo de storage que você usa e uma lista de problemas de configuração e recomendações.

Saiba mais sobre o link:https://docs.netapp.com/us-en/console-well-architected/learn-well-architected-dashboard.html["dashboard bem arquitetado"].

O painel de controle bem estruturado no Console está disponível para link:https://docs.netapp.com/us-en/console-well-architected/cvo/configuration-analysis-cvo.html["O Cloud Volumes ONTAP no Microsoft Azure."]



[[build-your-own-custom-rules]]
=== Crie suas próprias regras personalizadas

Escreva regras personalizadas em linguagem simples para garantir que seus sistemas sigam os padrões da sua organização e as melhores práticas da NetApp. Teste as regras com uma simulação e, em seguida, agende a execução delas em todos os seus ambientes.

https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["Saiba mais sobre regras personalizadas"]
