= Corrija, descarte e reative configurações para Cloud Volumes ONTAP no Microsoft Azure
:allow-uri-read: 




[[fix-dismiss-and-reactivate-configurations-for-cloud-volumes-ontap-in-microsoft-azure]]
=== Corrija, descarte e reative configurações para Cloud Volumes ONTAP no Microsoft Azure

O painel de controle bem estruturado no NetApp Console agora permite que você corrija recomendações de configuração para seus sistemas Cloud Volumes ONTAP.

Você também pode descartar uma ou mais configurações da análise de arquitetura bem estruturada. Isso permite ignorar configurações específicas que não se aplicam ao seu ambiente.

Se desejar incluir posteriormente uma configuração descartada, você pode reativá-la no painel de controle bem arquitetado. Isso restaura a configuração à análise e permite que você receba recomendações e correções para ela.

link:https://docs.netapp.com/us-en/console-well-architected/cvo/\improve-configurations-cvo.html["Corrija, descarte e reative configurações para Cloud Volumes ONTAP no Microsoft Azure"]
