---
sidebar: sidebar 
permalink: fsx/configuration-analysis-fsx.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations 
summary: O painel de controle bem arquitetado analisa regularmente as configurações do sistema de arquivos FSx for ONTAP para determinar se há algum problema de configuração. 
---
= Análise de configuração para Amazon FSx for NetApp ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O painel bem arquitetado no NetApp Console analisa regularmente as configurações do sistema de storage para determinar se há algum problema de configuração com seus sistemas de arquivos Amazon FSx for NetApp ONTAP. Quando problemas são encontrados, o painel mostra para você quais são os problemas e explica o que precisa ser alterado para garantir que seus sistemas de storage alcancem desempenho máximo, eficiência de custos e conformidade com as melhores práticas.

Principais funcionalidades incluem:

* Análise diária de configuração
* Validações automáticas de melhores práticas para sistemas de storage NetApp ONTAP e provedores de storage parceiros
* Observabilidade proativa
* Insights para ação


Diretiva não resolvida em <stdin> - include::well-architected-workloads.adoc[]



[[analysis-requirements]]
== Requisitos de análise

Para uma análise completa do sistema de arquivos, você deve fazer o seguinte:

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html#agent-console-deploy["Implantar um agente do NetApp Console"^] ou link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["associar um link"^] para configurar a conectividade entre o sistema de arquivos e o NetApp Console.
* Conceda permissões de _visualização, planejamento e análise_ em sua conta AWS.
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Aprenda como conceder permissões a uma conta da AWS"^]



Diretiva não resolvida em <stdin> - include::fsx-configurations.adoc[]

.O que vem a seguir
link:improve-configurations-fsx.html["Implemente configurações de sistema de arquivos FSx for ONTAP bem arquitetadas"]
